import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class AppleService {

  constructor() { }
  getImgAppleBanner() {
    return DATA_BANNER;
  }

  product = DATA_PRODUCT;
  getAppleProduct(id: any): Observable<any[]> {
    const apple = this.product.filter(x => x.brandId === 'apple' && x.categoryId === id);
    return of(apple)
  }

}

const DATA_BANNER = [{
  img: 'https://cdn.hoanghamobile.com/i/home/Uploads/2023/11/03/web-xiaomi-12-web.jpg',
  id: 'SP01'
},
{
  img: 'https://cdn.hoanghamobile.com/i/home/Uploads/2023/11/08/1200x375-lnv.png',
  id: 'SP01'
},
{
  img: 'https://cdn.hoanghamobile.com/i/home/Uploads/2023/10/31/1200x375-tuanlexiaomi-311023.jpg',
  id: 'SP01'
},
{
  img: 'https://cdn.hoanghamobile.com/i/home/Uploads/2023/11/10/1200x375-lenovo.png',
  id: 'SP01'
}
];

const DATA_PRODUCT = [
  {
    id: 'SP08',
    name: 'Túi xách Laptop SIMTOP SuperSlim 15.6"',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '',
    category: 'Điện thoại',
    categoryId: 'dien-thoai',
    brandId: 'oppo',
    idWish: '01',
    isLike: true,
  }, {
    id: 'SP07',
    name: 'OPPO Reno8 T 5G (8GB/128GB) - Chính hãng ',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '02',
    isLike: true,
    category: 'Điện thoại',
    brandId: 'oppo',
    categoryId: 'dien-thoai',
  },
  {
    id: 'SP06',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '',
    isLike: false, category: 'iphone',
    brandId: 'apple',
    categoryId: 'iphone',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '',
    category: 'iphone',
    brandId: 'apple',
    categoryId: 'iphone',
  }, {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '',
    category: 'Ipad',
    brandId: 'apple',
    categoryId: 'ipad',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '',
    category: 'Mac',
    brandId: 'apple',
    categoryId: 'mac',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '',
    category: 'Apple Watch',
    brandId: 'apple',
    categoryId: 'apple-watch',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '',
    category: 'AirPods',
    brandId: 'apple',
    categoryId: 'airpods',
  },
  {
    id: 'SP04',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: 'apple-watch.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '',
    category: 'Điện thoại',
    brandId: 'realme',
    categoryId: 'dien-thoai',
  },
  {
    id: 'SP03',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP02',
    name: 'Máy tính bảng Huawei Matepad LTE - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }, {
    id: 'SP08',
    name: 'Túi xách Laptop SIMTOP SuperSlim 15.6"',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '',
    idWish: '01',
    isLike: true, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }, {
    id: 'SP07',
    name: 'OPPO Reno8 T 5G (8GB/128GB) - Chính hãng ',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '02',
    isLike: true, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP06',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '',
    isLike: false, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP04',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: 'apple-watch.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP03',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP02',
    name: 'Máy tính bảng Huawei Matepad LTE - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }, {
    id: 'SP08',
    name: 'Túi xách Laptop SIMTOP SuperSlim 15.6"',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '',
    idWish: '01',
    isLike: true, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }, {
    id: 'SP07',
    name: 'OPPO Reno8 T 5G (8GB/128GB) - Chính hãng ',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '02',
    isLike: true, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP06',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '',
    isLike: false, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP04',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: 'apple-watch.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP03',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP02',
    name: 'Máy tính bảng Huawei Matepad LTE - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }, {
    id: 'SP08',
    name: 'Túi xách Laptop SIMTOP SuperSlim 15.6"',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '',
    idWish: '01',
    isLike: true, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }, {
    id: 'SP07',
    name: 'OPPO Reno8 T 5G (8GB/128GB) - Chính hãng ',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '02',
    isLike: true, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP06',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    idWish: '',
    isLike: false, category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP05',
    name: 'Ốp lưng GEAR4 D3O Crystal Palace Galaxy S22 Plus - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP04',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: 'apple-watch.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP03',
    name: 'Nokia C21 Plus (2GB/64GB) - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  },
  {
    id: 'SP02',
    name: 'Máy tính bảng Huawei Matepad LTE - Chính hãng',
    img: '14-prm-den.jpg',
    price: '4000000',
    priceSell: '29000000',
    isLike: false,
    idWish: '', category: 'Laptop',
    brandId: 'MSI',
    categoryId: 'lap-top',
  }
];